### ISSUE TITLE
iOS 9 Crash

### ISSUE THREAD

**Issue by jobrydev** [zhaoyabei/ZYBVideoPlayView#1]
`Optional(["old": 0, "new": 1, "kind": 1])
Optional(__C.AVPlayerItemStatus)
(lldb) `

**Comment by zhaoyabei** [comment]
Are you run with simulator or have some breakpoint? like `Optional(["old": 0, "new": 1, "kind": 1])
Optional(__C.AVPlayerItemStatus)` is just a print message that to tall you play status is changed(e.g. Failed) .
